version: '3'

services:
  indexer:
    container_name: indexer
    image: ltonetwork/indexer
    environment:
      - LTO_API_KEY=test
      - NODE_ENV=lto
    ports:
      - 80:80
    networks:
      - lto
    depends_on:
      - public-node

  public-node:
    container_name: public-node
    image: ltonetwork/public-node
    environment:
      - ENABLE_REST_API=true
      - LTO_WALLET_SEED=<seed of your wallet>
      - LTO_WALLET_PASSWORD=<a password for your wallet>
      - LTO_API_KEY=test
    networks:
      - lto

networks:
  lto:
    driver: bridge

